module.exports = [
    {id: 1, name: "Ambarawa"},
    {id: 2, name: "Ambon"},
    {id: 3, name: "Amlapura"},
    {id: 4, name: "Amuntai"},
    {id: 5, name: "Argamakmur"},
    {id: 6, name: "Atambua"},
    {id: 7, name: "Babo"},
    {id: 8, name: "Bagan Siapiapi"},
    {id: 316, name: "Bahaur, Kalteng"},
    {id: 9, name: "Bajawa"},
    {id: 10, name: "Balige"},
    {id: 11, name: "Balikpapan"},
    {id: 12, name: "Banda Aceh"},
    {id: 13, name: "Bandarlampung"},
    {id: 14, name: "Bandung"},
    {id: 15, name: "Bangkalan"},
    {id: 16, name: "Bangkinang"},
    {id: 17, name: "Bangko"},
    {id: 18, name: "Bangli"},
    {id: 19, name: "Banjar"},
    {id: 20, name: "Banjar Baru"},
    {id: 21, name: "Banjarmasin"},
    {id: 22, name: "Banjarnegara"},
    {id: 23, name: "Bantaeng"},
    {id: 24, name: "Banten"},
    {id: 25, name: "Bantul"},
    {id: 26, name: "Banyuwangi"},
    {id: 27, name: "Barabai"},
    {id: 28, name: "Barito"},
    {id: 29, name: "Barru"},
    {id: 30, name: "Batam"},
    {id: 31, name: "Batang"},
    {id: 32, name: "Batu"},
    {id: 33, name: "Baturaja"},
    {id: 34, name: "Batusangkar"},
    {id: 35, name: "Baubau"},
    {id: 36, name: "Bekasi"},
    {id: 37, name: "Bengkalis"},
    {id: 38, name: "Bengkulu"},
    {id: 39, name: "Benteng"},
    {id: 40, name: "Biak"},
    {id: 41, name: "Bima"},
    {id: 42, name: "Binjai"},
    {id: 43, name: "Bireuen"},
    {id: 44, name: "Bitung"},
    {id: 45, name: "Blitar"},
    {id: 46, name: "Blora"},
    {id: 47, name: "Bogor"},
    {id: 48, name: "Bojonegoro"},
    {id: 49, name: "Bondowoso"},
    {id: 50, name: "Bontang"},
    {id: 51, name: "Boyolali"},
    {id: 52, name: "Brebes"},
    {id: 53, name: "Bukit Tinggi"},
    {id: 315, name: "Bula Sbt, Maluku"},
    {id: 54, name: "Bulukumba"},
    {id: 55, name: "Buntok"},
    {id: 56, name: "Cepu"},
    {id: 57, name: "Ciamis"},
    {id: 58, name: "Cianjur"},
    {id: 59, name: "Cibinong"},
    {id: 60, name: "Cilacap"},
    {id: 61, name: "Cilegon"},
    {id: 62, name: "Cimahi"},
    {id: 63, name: "Cirebon"},
    {id: 64, name: "Curup"},
    {id: 65, name: "Demak"},
    {id: 66, name: "Denpasar"},
    {id: 67, name: "Depok"},
    {id: 68, name: "Dili"},
    {id: 69, name: "Dompu"},
    {id: 70, name: "Donggala"},
    {id: 71, name: "Dumai"},
    {id: 72, name: "Ende"},
    {id: 73, name: "Enggano"},
    {id: 74, name: "Enrekang"},
    {id: 75, name: "Fakfak"},
    {id: 76, name: "Garut"},
    {id: 77, name: "Gianyar"},
    {id: 78, name: "Gombong"},
    {id: 79, name: "Gorontalo"},
    {id: 80, name: "Gresik"},
    {id: 81, name: "Gunung Sitoli"},
    {id: 82, name: "Indramayu"},
    {id: 309, name: "Jakarta Barat"},
    {id: 308, name: "Jakarta Pusat"},
    {id: 310, name: "Jakarta Selatan"},
    {id: 311, name: "Jakarta Timur"},
    {id: 312, name: "Jakarta Utara"},
    {id: 83, name: "Jambi"},
    {id: 84, name: "Jayapura"},
    {id: 85, name: "Jember"},
    {id: 86, name: "Jeneponto"},
    {id: 87, name: "Jepara"},
    {id: 88, name: "Jombang"},
    {id: 89, name: "Kabanjahe"},
    {id: 90, name: "Kalabahi"},
    {id: 91, name: "Kalianda"},
    {id: 92, name: "Kandangan"},
    {id: 93, name: "Karanganyar"},
    {id: 94, name: "Karawang"},
    {id: 95, name: "Kasungan"},
    {id: 96, name: "Kayuagung"},
    {id: 97, name: "Kebumen"},
    {id: 98, name: "Kediri"},
    {id: 99, name: "Kefamenanu"},
    {id: 100, name: "Kendal"},
    {id: 101, name: "Kendari"},
    {id: 102, name: "Kertosono"},
    {id: 103, name: "Ketapang"},
    {id: 104, name: "Kisaran"},
    {id: 105, name: "Klaten"},
    {id: 106, name: "Kolaka"},
    {id: 107, name: "Kota Baru Pulau Laut"},
    {id: 108, name: "Kota Bumi"},
    {id: 109, name: "Kota Jantho"},
    {id: 110, name: "Kotamobagu"},
    {id: 111, name: "Kuala Kapuas"},
    {id: 112, name: "Kuala Kurun"},
    {id: 113, name: "Kuala Pembuang"},
    {id: 114, name: "Kuala Tungkal"},
    {id: 115, name: "Kudus"},
    {id: 116, name: "Kuningan"},
    {id: 117, name: "Kupang"},
    {id: 118, name: "Kutacane"},
    {id: 119, name: "Kutoarjo"},
    {id: 120, name: "Labuhan"},
    {id: 121, name: "Lahat"},
    {id: 122, name: "Lamongan"},
    {id: 123, name: "Langsa"},
    {id: 124, name: "Larantuka"},
    {id: 125, name: "Lawang"},
    {id: 126, name: "Lhoseumawe"},
    {id: 127, name: "Limboto"},
    {id: 128, name: "Lubuk Basung"},
    {id: 129, name: "Lubuk Linggau"},
    {id: 130, name: "Lubuk Pakam"},
    {id: 131, name: "Lubuk Sikaping"},
    {id: 132, name: "Lumajang"},
    {id: 133, name: "Luwuk"},
    {id: 134, name: "Madiun"},
    {id: 135, name: "Magelang"},
    {id: 136, name: "Magetan"},
    {id: 137, name: "Majalengka"},
    {id: 138, name: "Majene"},
    {id: 139, name: "Makale"},
    {id: 140, name: "Makassar"},
    {id: 141, name: "Malang"},
    {id: 142, name: "Mamuju"},
    {id: 143, name: "Manna"},
    {id: 144, name: "Manokwari"},
    {id: 145, name: "Marabahan"},
    {id: 146, name: "Maros"},
    {id: 147, name: "Martapura Kalsel"},
    {id: 314, name: "Masamba, Sulsel"},
    {id: 148, name: "Masohi"},
    {id: 149, name: "Mataram"},
    {id: 150, name: "Maumere"},
    {id: 151, name: "Medan"},
    {id: 152, name: "Mempawah"},
    {id: 153, name: "Menado"},
    {id: 154, name: "Mentok"},
    {id: 155, name: "Merauke"},
    {id: 156, name: "Metro"},
    {id: 157, name: "Meulaboh"},
    {id: 158, name: "Mojokerto"},
    {id: 159, name: "Muara Bulian"},
    {id: 160, name: "Muara Bungo"},
    {id: 161, name: "Muara Enim"},
    {id: 162, name: "Muara Teweh"},
    {id: 163, name: "Muaro Sijunjung"},
    {id: 164, name: "Muntilan"},
    {id: 165, name: "Nabire"},
    {id: 166, name: "Negara"},
    {id: 167, name: "Nganjuk"},
    {id: 168, name: "Ngawi"},
    {id: 169, name: "Nunukan"},
    {id: 170, name: "Pacitan"},
    {id: 171, name: "Padang"},
    {id: 172, name: "Padang Panjang"},
    {id: 173, name: "Padang Sidempuan"},
    {id: 174, name: "Pagaralam"},
    {id: 175, name: "Painan"},
    {id: 176, name: "Palangkaraya"},
    {id: 177, name: "Palembang"},
    {id: 178, name: "Palopo"},
    {id: 179, name: "Palu"},
    {id: 180, name: "Pamekasan"},
    {id: 181, name: "Pandeglang"},
    {id: 182, name: "Pangka_"},
    {id: 183, name: "Pangkajene Sidenreng"},
    {id: 184, name: "Pangkalan Bun"},
    {id: 185, name: "Pangkalpinang"},
    {id: 186, name: "Panyabungan"},
    {id: 187, name: "Par_"},
    {id: 188, name: "Parepare"},
    {id: 189, name: "Pariaman"},
    {id: 190, name: "Pasuruan"},
    {id: 191, name: "Pati"},
    {id: 192, name: "Payakumbuh"},
    {id: 193, name: "Pekalongan"},
    {id: 194, name: "Pekan Baru"},
    {id: 195, name: "Pemalang"},
    {id: 196, name: "Pematangsiantar"},
    {id: 197, name: "Pendopo"},
    {id: 198, name: "Pinrang"},
    {id: 199, name: "Pleihari"},
    {id: 200, name: "Polewali"},
    {id: 201, name: "Pondok Gede"},
    {id: 202, name: "Ponorogo"},
    {id: 203, name: "Pontianak"},
    {id: 204, name: "Poso"},
    {id: 205, name: "Prabumulih"},
    {id: 206, name: "Praya"},
    {id: 207, name: "Probolinggo"},
    {id: 208, name: "Purbalingga"},
    {id: 209, name: "Purukcahu"},
    {id: 210, name: "Purwakarta"},
    {id: 211, name: "Purwodadigrobogan"},
    {id: 212, name: "Purwokerto"},
    {id: 213, name: "Purworejo"},
    {id: 214, name: "Putussibau"},
    {id: 215, name: "Raha"},
    {id: 216, name: "Rangkasbitung"},
    {id: 217, name: "Rantau"},
    {id: 218, name: "Rantauprapat"},
    {id: 219, name: "Rantepao"},
    {id: 220, name: "Rembang"},
    {id: 221, name: "Rengat"},
    {id: 222, name: "Ruteng"},
    {id: 223, name: "Sabang"},
    {id: 224, name: "Salatiga"},
    {id: 225, name: "Samarinda"},
    {id: 313, name: "Sambas, Kalbar"},
    {id: 226, name: "Sampang"},
    {id: 227, name: "Sampit"},
    {id: 228, name: "Sanggau"},
    {id: 229, name: "Sawahlunto"},
    {id: 230, name: "Sekayu"},
    {id: 231, name: "Selong"},
    {id: 232, name: "Semarang"},
    {id: 233, name: "Sengkang"},
    {id: 234, name: "Serang"},
    {id: 235, name: "Serui"},
    {id: 236, name: "Sibolga"},
    {id: 237, name: "Sidikalang"},
    {id: 238, name: "Sidoarjo"},
    {id: 239, name: "Sigli"},
    {id: 240, name: "Singaparna"},
    {id: 241, name: "Singaraja"},
    {id: 242, name: "Singkawang"},
    {id: 243, name: "Sinjai"},
    {id: 244, name: "Sintang"},
    {id: 245, name: "Situbondo"},
    {id: 246, name: "Slawi"},
    {id: 247, name: "Sleman"},
    {id: 248, name: "Soasiu"},
    {id: 249, name: "Soe"},
    {id: 250, name: "Solo"},
    {id: 251, name: "Solok"},
    {id: 252, name: "Soreang"},
    {id: 253, name: "Sorong"},
    {id: 254, name: "Sragen"},
    {id: 255, name: "Stabat"},
    {id: 256, name: "Subang"},
    {id: 257, name: "Sukabumi"},
    {id: 258, name: "Sukoharjo"},
    {id: 259, name: "Sumbawa Besar"},
    {id: 260, name: "Sumedang"},
    {id: 261, name: "Sumenep"},
    {id: 262, name: "Sungai Liat"},
    {id: 263, name: "Sungai Penuh"},
    {id: 264, name: "Sungguminasa"},
    {id: 265, name: "Surabaya"},
    {id: 266, name: "Surakarta"},
    {id: 267, name: "Tabanan"},
    {id: 268, name: "Tahuna"},
    {id: 269, name: "Takalar"},
    {id: 270, name: "Takengon"},
    {id: 271, name: "Tamiang Layang"},
    {id: 272, name: "Tanah Grogot"},
    {id: 273, name: "Tangerang"},
    {id: 274, name: "Tanjung Balai"},
    {id: 275, name: "Tanjung Enim"},
    {id: 276, name: "Tanjung Pandan"},
    {id: 277, name: "Tanjung Pinang"},
    {id: 278, name: "Tanjung Redep"},
    {id: 279, name: "Tanjung Selor"},
    {id: 280, name: "Tapak Tuan"},
    {id: 281, name: "Tarakan"},
    {id: 282, name: "Tarutung"},
    {id: 283, name: "Tasikmalaya"},
    {id: 284, name: "Tebing Tinggi"},
    {id: 285, name: "Tegal"},
    {id: 286, name: "Temanggung"},
    {id: 287, name: "Tembilahan"},
    {id: 288, name: "Tenggarong"},
    {id: 289, name: "Ternate"},
    {id: 290, name: "Tolitoli"},
    {id: 291, name: "Tondano"},
    {id: 292, name: "Trenggalek"},
    {id: 293, name: "Tual"},
    {id: 294, name: "Tuban"},
    {id: 295, name: "Tulung Agung"},
    {id: 296, name: "Ujung Berung"},
    {id: 297, name: "Ungaran"},
    {id: 298, name: "Waikabubak"},
    {id: 299, name: "Waingapu"},
    {id: 300, name: "Wamena"},
    {id: 301, name: "Watampone"},
    {id: 302, name: "Watansoppeng"},
    {id: 303, name: "Wates"},
    {id: 304, name: "Wonogiri"},
    {id: 305, name: "Wonosari"},
    {id: 306, name: "Wonosobo"},
    {id: 307, name: "Yogyakarta"}
];